### ISSUE TITLE
Erigon - stucked block 

### ISSUE THREAD

**Issue by mnguyen-io** [allada/bsc-archive-snapshot#16]
Hi - have you run into this issue where erigon appears to be stuck at a single block? I tried to see if using --badblock would allow it to skip, but probably not the right way to do it.. and even still it doesn't work.

```
Mar 02 16:34:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:34:06.293] [p2p] GoodPeers                          eth66=38
Mar 02 16:34:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:34:06.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="579.18 MiB" sys="1.09 GiB"
Mar 02 16:34:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:34:36.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="709.26 MiB" sys="1.09 GiB"
Mar 02 16:35:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:35:06.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="854.67 MiB" sys="1.09 GiB"
Mar 02 16:35:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:35:36.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="543.80 MiB" sys="1.09 GiB"
Mar 02 16:36:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:36:06.293] [p2p] GoodPeers                          eth66=38
Mar 02 16:36:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:36:06.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="673.06 MiB" sys="1.09 GiB"
Mar 02 16:36:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:36:36.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="815.58 MiB" sys="1.09 GiB"
Mar 02 16:37:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:37:06.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="515.15 MiB" sys="1.09 GiB"
Mar 02 16:37:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:37:36.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="672.62 MiB" sys="1.09 GiB"
Mar 02 16:38:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:38:06.293] [p2p] GoodPeers                          eth66=38
Mar 02 16:38:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:38:06.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="820.81 MiB" sys="1.09 GiB"
Mar 02 16:38:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:38:36.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="530.59 MiB" sys="1.09 GiB"
Mar 02 16:39:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:39:06.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="653.44 MiB" sys="1.09 GiB"
Mar 02 16:39:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:39:36.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="785.85 MiB" sys="1.09 GiB"
Mar 02 16:40:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:40:06.293] [p2p] GoodPeers                          eth66=38
Mar 02 16:40:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:40:06.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="484.32 MiB" sys="1.09 GiB"
Mar 02 16:40:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:40:36.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="610.96 MiB" sys="1.09 GiB"
Mar 02 16:41:06  erigon-2022.02.04[4042435]: [INFO] [03-02|16:41:06.777] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="737.80 MiB" sys="1.09 GiB"
Mar 02 16:41:36  erigon-2022.02.04[4042435]: [INFO] [03-02|16:41:36.778] [1/16 Headers] Wrote block headers       number=15597806 blk/second=0.000 alloc="872.93 MiB" sys="1.09 GiB"

```

**Comment by mnguyen-io** [comment]
On another note - if you still maintain a copy of the BSC Geth snapshot, is it possible to get a copy? I recall there was a price so would like to know what that cost is as well. Thank you

**Comment by allada** [comment]
I actually found a bug when using `--bad.block` referenced here:
https://github.com/allada/bsc-archive-snapshot/issues/14#issuecomment-1057463340

It might be best to wait until my new sync is done. I'd estimate ~1 week.

As for if I still have a copy of `geth` database, yes I do, but it's in deep-archive storage and hasn't been updated since ~mid December. The estimate on how much it will cost to transfer is fairly complex. There's about 25TB (IIRC). To restore the data in bulk will likely take multiple days (I'd count on 10 days) and cost around $100USD. To store the data outside of Deep Glacier storage will cost around $550USD. To transfer the data outside of the data center will cost around $2,500USD. (These estimates assume ~1 month of Standard storage while it is copied/transferred).

**Comment by mnguyen-io** [comment]
Thanks for the info @allada . Out of curiosity - how long has your BSC Erigon node been running for? Have you ever have to start from scratch again after having it working for X amount of time? Currently I would like to get it up as an alternative RPC service while Geth syncs which appears like it'll take a month or more

**Comment by allada** [comment]
I have not had to restart my erigon node for a couple months, however twice a bug was found on the BSC chain that erigon patched and I had to do some work to fix. #14 is one of these cases. Since I use zfs I can create snapshots and upload them in the background with only having a few seconds of down time, if you took the time to modify `erigon` you could do this with near zero down time. This means that in the event of something going wrong on the node, I can easily roll back to the last version.

As for `geth`, don't under-estimate how expensive it is to run a full geth archive node. `geth` uses an insane amount of disk space and it takes a very long time to sync back up to latest blocks. I was spending around $1,000USD/mo to just run 1/16ish of the chain at a time and this was on spot instances (which are about 1/3 the price of normal AWS instances).

The big advantage to erigon is that it is able to work with a distributed database and you can have one node write to the database and many nodes read from it to serve the RPC requests. This significantly reduces the cost and improves throughput by orders of magnitude. The down side of erigon is that it is new and has bugs.

**Comment by mnguyen-io** [comment]
Closing this - not much to do here. I'll keep an eye out for your next snapshot. Appreciate all your work and effort
