### ISSUE TITLE
Euler Upgrade

### ISSUE THREAD

**Issue by Prof-SD** [allada/bsc-archive-snapshot#21]
Hi,

Just wanted to check before downloading, do these snapshots work with the updated Erigon after this weeks hard fork? As I understand it, there is some re-syncing required after recent Erigon alpha upgrades.

Thanks for all of the work you do maintaining this!

Thanks
Scott

**Comment by allada** [comment]
I believe so, I did fetch the latest `erigon` a few days ago and and checked it just now and it is still running and processing new blocks. Thanks for pointing this out though, because I'm trying to build a new node in prep for BSC hitting the 8GB database limit. This new node requires a full resync with the database page size set to 16k (default is 4k) This will give ~32GB of database size before it will fall over.

Just be on notice that in a few months this node you are using will fall over and without notice.

I don't have an ETA on when the new node will be done. Possibly in a few weeks if no problems occur.

**Comment by Prof-SD** [comment]
Awesome. Thank you so much!
