### ISSUE TITLE
ETH vs BSC Archive Nodes`

### ISSUE THREAD

**Issue by hub-il** [allada/bsc-archive-snapshot#36]
We run a GETH archive node for ETH that is currently around 12TB.  Is there something different about BSC that makes an archive node 30TB for BSC using GETH?  It just seems so much larger I'd like to understand if there is something unique about BSC that makes it use twice the space.  If you don't know then you can just close this issue.  I appreciate your time and effort that you put into this project.

**Comment by allada** [comment]
I don't use `geth` any more and opt for using `erigon` instead. This is because `geth` is very inefficient in the way it stores archive data, erigon is significantly more efficient.

ETH has a chain speed of ~1 block per 15 seconds. BSC has a chain speed of about 1 per 4 seconds, so you can see why it has so many more blocks.
